# Generated by Django 5.0.4 on 2024-08-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Graduated', 'Graduated'), ('Transferred', 'Transferred'), ('Dropped', 'Dropped')], max_length=20, null=True),
        ),
    ]
