# Generated by Django 5.0.4 on 2024-08-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_student_delete_status_student_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Graduated', 'Graduated'), ('Transferred', 'Transferred'), ('Dropped', 'Dropped')], default='Active', max_length=20, null=True),
        ),
    ]
