# Generated by Django 5.0.4 on 2024-08-26 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_student_current_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20)),
                ('alternative_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField()),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('employment_status', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Temporary', 'Temporary')], max_length=20)),
                ('date_joined', models.DateField()),
                ('years_of_experience', models.PositiveIntegerField()),
                ('highest_degree', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=200)),
                ('graduation_year', models.PositiveIntegerField()),
                ('certifications', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('subjects_taught', models.TextField()),
                ('classes_assigned', models.TextField()),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_relationship', models.CharField(max_length=50)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
                ('bio', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__name'],
                'indexes': [models.Index(fields=['employee_id'], name='home_teache_employe_b37cb5_idx'), models.Index(fields=['national_id'], name='home_teache_nationa_2af572_idx')],
            },
        ),
    ]
