# Generated by Django 5.0.4 on 2024-08-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='delete_status',
            field=models.BooleanField(default=False),
        ),
    ]
