# Generated by Django 5.0.4 on 2024-08-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_attendance_class_subject_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
