# Generated by Django 5.0.4 on 2024-08-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_class_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('class_group', 'subject')},
        ),
        migrations.AddField(
            model_name='classsubject',
            name='ending_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='starting_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='classsubject',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='classsubject',
            name='term',
        ),
    ]
