# Generated by Django 5.0.4 on 2024-09-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_classsubject_day'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together=set(),
        ),
    ]
