# Generated by Django 5.0.4 on 2024-09-16 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_teacherattendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherAttendance',
        ),
    ]
