# Generated by Django 5.0.4 on 2024-09-17 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_attendance_academic_year_classsubject_academic_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.BooleanField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.academicyear')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'academic_year', 'date')},
            },
        ),
    ]
