# Generated by Django 5.0.4 on 2024-09-17 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_teacherattendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherattendance',
            unique_together={('teacher', 'academic_year', 'date')},
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_teacher_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.academicyear'),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.teacher'),
        ),
        migrations.RemoveField(
            model_name='teacherattendance',
            name='status',
        ),
    ]
