# Generated by Django 5.0.4 on 2024-09-17 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_teacherattendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherAttendance',
        ),
    ]
